[pytest]
pythonpath = .
markers =
    smoke: быстрые проверки api
    auth: тесты авторизации
    create: создание booking
    read: чтение booking
    update: обновление booking
    delete: удаление booking
    negative: негативные тесты
    filters: фильтрация booking

    cart: тесты корзины 
    login: тесты входа 
    logout: тесты выхода
    signup: тесты регистрации
    products: продуктовые тесты

addopts =
    -v
    --strict-markers
    --disable-warnings
    -rA

testpaths =
    api/tests
    ui/tests